# Generated by Django 4.1.7 on 2023-03-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_availability_docappointment_patientappointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='non_available',
        ),
    ]
