# Generated by Django 4.1.7 on 2023-03-03 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_doctorinfo_non_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docappointment',
            name='appointment',
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='appointments',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='hospital.docappointment'),
        ),
        migrations.AddField(
            model_name='docappointment',
            name='appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='hospital.availability'),
        ),
    ]
