# Generated by Django 4.1.7 on 2023-03-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_docappointment_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='completed',
            field=models.ManyToManyField(blank=True, default=None, related_name='appointmentscomplete', to='hospital.docappointment'),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='cancelled',
            field=models.ManyToManyField(blank=True, default=None, related_name='patientcancelled', to='hospital.docappointment'),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='completed',
            field=models.ManyToManyField(blank=True, default=None, related_name='patientcomplete', to='hospital.docappointment'),
        ),
        migrations.AlterField(
            model_name='docappointment',
            name='appointment',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
