# Generated by Django 4.1.7 on 2023-03-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_doctorinfo_completed_patientinfo_cancelled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docappointment',
            name='appointment',
        ),
        migrations.AddField(
            model_name='docappointment',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docappointment',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
