# Generated by Django 4.1.7 on 2023-03-07 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugpic', models.ImageField(default=None, upload_to='images/drugs')),
                ('name', models.CharField(max_length=150)),
                ('descr', models.TextField()),
                ('prescription', models.TextField()),
                ('orders', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucessful', models.BooleanField(default=False)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_drugs', to='hospital.pharmacy')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='cancelled_orders',
            field=models.ManyToManyField(blank=True, default=None, related_name='orders_cancelled', to='hospital.order'),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='cart',
            field=models.ManyToManyField(blank=True, default=None, related_name='drugs_carted', to='hospital.order'),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='successful_orders',
            field=models.ManyToManyField(blank=True, default=None, related_name='orders_successful', to='hospital.order'),
        ),
    ]
