# Generated by Django 4.1.7 on 2023-03-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_pharmacy_order_patientinfo_cancelled_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='instock',
            field=models.IntegerField(default=0),
        ),
    ]
