# Generated by Django 4.1.7 on 2023-03-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_pharmacy_instock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='cancelled',
        ),
    ]
