# Generated by Django 4.1.7 on 2023-03-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_order_amount_order_itemprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='completed',
            field=models.ManyToManyField(blank=True, default=None, related_name='patientcomplete', to='hospital.patientappointment'),
        ),
    ]
