# Generated by Django 4.1.7 on 2023-03-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_patientinfo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='completed',
            field=models.ManyToManyField(blank=True, default=None, related_name='appointmentscomplete', to='hospital.patientappointment'),
        ),
    ]
