# Generated by Django 3.2.6 on 2023-03-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_deletedappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
