# Generated by Django 3.2.6 on 2023-03-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_user_is_email_verfied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_email_verfied',
            new_name='is_email_verified',
        ),
    ]
