# Generated by Django 3.2.6 on 2023-03-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_rename_is_email_verfied_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_change',
            field=models.BooleanField(default=False),
        ),
    ]
