# Generated by Django 3.2.6 on 2023-03-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_user_profile_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_change',
            new_name='is_profile_change',
        ),
    ]
