# Generated by Django 3.2.6 on 2023-03-12 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_alter_patientinfo_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='healthcare', to=settings.AUTH_USER_MODEL),
        ),
    ]
