# Generated by Django 3.2.6 on 2023-03-18 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_alter_doctorinfo_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_profile_change',
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patientappoint', to='hospital.docappointment'),
        ),
    ]
